apiVersion: apps/v1
kind: Deployment
metadata:
  name: logserver
  namespace: pitstop
  labels:
    env: production  
spec:
  replicas: 1
  selector:
    matchLabels:
      name: logserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1    
  template:
    metadata:
      name: logserver
      labels:
        name: logserver 
    spec:
      containers:
        - name: logserver 
          image: datalust/seq:latest
          env:
            - name: ACCEPT_EULA 
              value: "Y" 
          ports:
            - containerPort: 80
      


---
apiVersion: v1
kind: Service
metadata:
  name: logserver
  namespace: pitstop  
spec:
  selector:
    name: logserver 
  type: ClusterIP
  ports:
    - name: "http-5341"
      targetPort: 80
      port: 5341 
      