apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
  namespace: pitstop
  labels:
    env: production  
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mailserver
  template:
    metadata:
      name: mailserver
      labels:
        name: mailserver 
    spec:
      containers:
        - name: mailserver 
          image: maildev/maildev:1.1.0
          ports:
            - containerPort: 25
            - containerPort: 80



---
apiVersion: v1
kind: Service
metadata:
  name: mailserver
  namespace: pitstop  
spec:
  selector:
    name: mailserver 
  type: ClusterIP
  ports:
    - name: "smtp"
      targetPort: 25
      port: 25
    - name: "web"
      targetPort: 80
      port: 4000