---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq       
  namespace: pitstop
data: 
  rabbitmq.conf:  |
    default_user = rabbitmquser
    default_pass = DEBmbwkSrzy9D1T9cJfa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: pitstop
  labels:
    env: production  
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq
  template:
    metadata:
      name: rabbitmqpod
      labels:
        name: rabbitmq 
    spec:
      containers:
        - name: rabbitmq 
          image: rabbitmq:3-management-alpine
          env:
            - name: RABBITMQ_CONFIG_FILE 
              value: /etc/pitstop/rabbitmq.conf 
          ports:
            - containerPort: 15672
            - containerPort: 5672
          volumeMounts:
            - name: myvolume 
              mountPath: "/etc/pitstop"
              readOnly: true
      restartPolicy: Always        
      volumes:
        - name: myvolume
          configMap:
            name: rabbitmq    



    
  


---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    name: rabbitmq 
  type: ClusterIP
  ports:
    - name: "http-admin"
      targetPort: 15672
      port: 15672
    - name: "data"
      targetPort: 5672
      port: 5672 





        
             

              
          
          
      
      
     




