apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: pitstop
  labels:
    env: production  
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sqlserver
  template:
    metadata:
      name: sqlserver
      labels:
        name: sqlserver 
    spec:
      containers:
        - name: sqlserver  
          image: mcr.microsoft.com/azure-sql-edge
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA 
              value: "Y"
            - name: MSSQL_PID 
              value: "Developer" 
            - name: SA_PASSWORD 
              value: "8jkGh47hnDw89Haq8LN2"


            


---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: pitstop  
spec:
  selector:
    name: sqlserver 
  type: ClusterIP
  ports:
    - name: "tds"
      targetPort: 1433
      port: 1433
