---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeservice
  namespace: pitstop
  labels:
    env: production  
spec:
  replicas: 1
  selector:
    matchLabels:
      name: timeservice
  template:
    metadata:
      name: timeservicepod
      labels:
        name: timeservice 
    spec:
      containers:
        - name: timeservice 
          image: pitstop/timeservice:1.0
          env:
            - name: DOTNET_ENVIRONMENT 
              value: Production 