---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiclemanagementapi
  namespace: pitstop
  labels:
    env: production  
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      name: vehiclemanagementapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: vehiclemanagementapipod
      labels:
        name: vehiclemanagementapi 
    spec:
      containers:
        - name: vehiclemanagementapi 
          image: pitstop/vehiclemanagementapi:1.0
          env:
            - name: ASPNETCORE_ENVIRONMENT 
              value: Production 
          ports:
            - containerPort: 5000



---
apiVersion: v1
kind: Service
metadata:
  name: vehiclemanagementapi
  namespace: pitstop  
spec:
  selector:
    name: vehiclemanagementapi 
  type: ClusterIP
  ports:
    - name: "http-5000"
      targetPort: 5000
      port: 5000 