---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: pitstop
  labels:
    env: production  
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      name: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: webapppod
      labels:
        name: webapp 
    spec:
      containers:
        - name: webapp 
          image: pitstop/webapp:1.0
          env:
            - name: ASPNETCORE_ENVIRONMENT 
              value: Production
          ports:
            - containerPort: 7005



---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: pitstop  
spec:
  selector:
    name: webapp 
  type: LoadBalancer
  ports:
    - name: "7005"
      targetPort: 7005
      port: 80 