---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshopmanagementapi
  namespace: pitstop
  labels:
    env: production  
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      name: workshopmanagementapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: workshopmanagementapipod
      labels:
        name: workshopmanagementapi 
    spec:
      containers:
        - name: workshopmanagementapi 
          image:  pitstop/workshopmanagementapi:1.0
          env:
            - name: ASPNETCORE_ENVIRONMENT 
              value: Production 
          ports:
            - containerPort: 5200



---
apiVersion: v1
kind: Service
metadata:
  name: workshopmanagementapi
  namespace: pitstop  
spec:
  selector:
    name: workshopmanagementapi 
  type: ClusterIP
  ports:
    - name: http-5200
      targetPort: 5200
      port: 5200 